test script

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -78,29 +78,29 @@ jobs:
         with:
           python-version: 3.6
 
-      - name: set-release-env
-        shell: bash
-        run: |
-          RELEASE_TAG="${{ github.event.release.tag_name }}"
-          if [[ $RELEASE_TAG =~ ^v?([[:digit:]\.]+)(-rc)? ]]; then
-            VERSION="${BASH_REMATCH[1]}"
-            if [[ "${{ github.event.release.prerelease}}" == "true" ]]; then
-              if [[ -z "${BASH_REMATCH[2]}" ]]; then
-                echo "A test release tag should end with \"-rc\""
-                exit 1
-              fi
-
-              # for staging builds we append the build number so we have
-              # distinct version numbers between prod and test pypi.
-              VERSION="$VERSION.$GITHUB_RUN_NUMBER"
-            fi
-
-          else
-            echo "Unable to parse deployment version from $RELEASE_TAG"
-            exit 1
-          fi
-
-          echo "VERSION=$VERSION" >> $GITHUB_ENV
+#      - name: set-release-env
+#        shell: bash
+#        run: |
+#          RELEASE_TAG="${{ github.event.release.tag_name }}"
+#          if [[ $RELEASE_TAG =~ ^v?([[:digit:]\.]+)(-rc)? ]]; then
+#            VERSION="${BASH_REMATCH[1]}"
+#            if [[ "${{ github.event.release.prerelease}}" == "true" ]]; then
+#              if [[ -z "${BASH_REMATCH[2]}" ]]; then
+#                echo "A test release tag should end with \"-rc\""
+#                exit 1
+#              fi
+#
+#              # for staging builds we append the build number so we have
+#              # distinct version numbers between prod and test pypi.
+#              VERSION="$VERSION.$GITHUB_RUN_NUMBER"
+#            fi
+#
+#          else
+#            echo "Unable to parse deployment version from $RELEASE_TAG"
+#            exit 1
+#          fi
+#
+#          echo "VERSION=$VERSION" >> $GITHUB_ENV
 
       # ensure that the version file in the package will have the correct version
       # matching the name of the tag
