test script

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -172,47 +172,47 @@ jobs:
       - name: install-the-artifact-wheel
         shell: bash
         run: |
+          pip install wheel
+          pip install dist/synapseclient-2.3.0-py3-none-any.whl
 
-          pip install dist/synapseclient*.whl
 
-          
 
-      - name: check-pypi
-        shell: bash
-        run: |
-          if [[ "${{ github.event.release.prerelease}}" == "false" ]]; then
-            PYPI_INDEX_URL="https://pypi.org/simple/"
-          else
-            PYPI_INDEX_URL="https://test.pypi.org/simple/"
-          fi
-
-          RELEASE_TAG="${{ github.event.release.tag_name }}"
-          if [[ $RELEASE_TAG =~ ^v?([[:digit:]\.]+)(-rc)? ]]; then
-            VERSION="${BASH_REMATCH[1]}"
-            if [[ "${{ github.event.release.prerelease}}" == "true" ]]; then
-              VERSION="$VERSION.$GITHUB_RUN_NUMBER"
-            fi
-          else
-            echo "Unrecognized release tag"
-            exit 1
-          fi
-
-          # it can take some time for the packages to become available in pypi after uploading
-          for i in 5 10 20 40; do
-            if pip3 install --index-url $PYPI_INDEX_URL --extra-index-url https://pypi.org/simple "synapseclient==$VERSION"; then
-              ACTUAL_VERSION=$(synapse --version)
-
-              if [ -n "$(echo "$ACTUAL_VERSION" | grep -oF "$VERSION")" ]; then
-                echo "Successfully installed version $VERSION"
-                exit 0
-              else
-                echo "Expected version $VERSION, found $ACTUAL_VERSION instead"
-                exit 1
-              fi
-            fi
-
-            sleep $i
-          done
-
-          echo "Failed to install expected version $VERSION"
-          exit 1
+#      - name: check-pypi
+#        shell: bash
+#        run: |
+#          if [[ "${{ github.event.release.prerelease}}" == "false" ]]; then
+#            PYPI_INDEX_URL="https://pypi.org/simple/"
+#          else
+#            PYPI_INDEX_URL="https://test.pypi.org/simple/"
+#          fi
+#
+#          RELEASE_TAG="${{ github.event.release.tag_name }}"
+#          if [[ $RELEASE_TAG =~ ^v?([[:digit:]\.]+)(-rc)? ]]; then
+#            VERSION="${BASH_REMATCH[1]}"
+#            if [[ "${{ github.event.release.prerelease}}" == "true" ]]; then
+#              VERSION="$VERSION.$GITHUB_RUN_NUMBER"
+#            fi
+#          else
+#            echo "Unrecognized release tag"
+#            exit 1
+#          fi
+#
+#          # it can take some time for the packages to become available in pypi after uploading
+#          for i in 5 10 20 40; do
+#            if pip3 install --index-url $PYPI_INDEX_URL --extra-index-url https://pypi.org/simple "synapseclient==$VERSION"; then
+#              ACTUAL_VERSION=$(synapse --version)
+#
+#              if [ -n "$(echo "$ACTUAL_VERSION" | grep -oF "$VERSION")" ]; then
+#                echo "Successfully installed version $VERSION"
+#                exit 0
+#              else
+#                echo "Expected version $VERSION, found $ACTUAL_VERSION instead"
+#                exit 1
+#              fi
+#            fi
+#
+#            sleep $i
+#          done
+#
+#          echo "Failed to install expected version $VERSION"
+#          exit 1
